name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11.5"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: disertatie
        environment-file: conda.yml
        python-version: ${{ matrix.python-version }}
        auto-activate-base: false
    - run: |
        conda info
        conda list
        conda init --all
    - name: Analysing the code with pylint
      shell: bash -l {0}
      run: |
        pylint $(git ls-files '*.py') --fail-under=8
    - name: Generate badge
      shell: bash -l {0}
      run: |
        python3 pylintbadge.py .
